<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThirdV3.proto

namespace ThirdV3;

/**
 * Protobuf enum <code>ThirdV3.LocationType</code>
 */
class LocationType
{
    /**
     * <code>_ = 0;</code>
     */
    const _ = 0;
    /**
     * <code>GPS = 1;</code>
     */
    const GPS = 1;
    /**
     * <code>NET = 2;</code>
     */
    const NET = 2;
    /**
     * <code>OTHER = 3;</code>
     */
    const OTHER = 3;
}

