<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThirdV3.proto

namespace ThirdV3;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>ThirdV3.Map</code>
 */
class Map extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string uid = 1;</code>
     */
    private $uid = '';
    /**
     * <code>double lng = 2;</code>
     */
    private $lng = 0.0;
    /**
     * <code>double lat = 3;</code>
     */
    private $lat = 0.0;
    /**
     * <code>double speed = 4;</code>
     */
    private $speed = 0.0;
    /**
     * <code>.ThirdV3.LocationType loc_type = 5;</code>
     */
    private $loc_type = 0;

    public function __construct() {
        \GPBMetadata\ThirdV3::initOnce();
        parent::__construct();
    }

    /**
     * <code>string uid = 1;</code>
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * <code>string uid = 1;</code>
     */
    public function setUid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid = $var;
    }

    /**
     * <code>double lng = 2;</code>
     */
    public function getLng()
    {
        return $this->lng;
    }

    /**
     * <code>double lng = 2;</code>
     */
    public function setLng($var)
    {
        GPBUtil::checkDouble($var);
        $this->lng = $var;
    }

    /**
     * <code>double lat = 3;</code>
     */
    public function getLat()
    {
        return $this->lat;
    }

    /**
     * <code>double lat = 3;</code>
     */
    public function setLat($var)
    {
        GPBUtil::checkDouble($var);
        $this->lat = $var;
    }

    /**
     * <code>double speed = 4;</code>
     */
    public function getSpeed()
    {
        return $this->speed;
    }

    /**
     * <code>double speed = 4;</code>
     */
    public function setSpeed($var)
    {
        GPBUtil::checkDouble($var);
        $this->speed = $var;
    }

    /**
     * <code>.ThirdV3.LocationType loc_type = 5;</code>
     */
    public function getLocType()
    {
        return $this->loc_type;
    }

    /**
     * <code>.ThirdV3.LocationType loc_type = 5;</code>
     */
    public function setLocType($var)
    {
        GPBUtil::checkEnum($var, \ThirdV3\LocationType::class);
        $this->loc_type = $var;
    }

}

