<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThirdV3.proto

namespace GPBMetadata;

class ThirdV3
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aba010a0d546869726456332e70726f746f12075468697264563322640a" .
            "034d6170120b0a03756964180120012809120b0a036c6e67180220012801" .
            "120b0a036c6174180320012801120d0a0573706565641804200128011227" .
            "0a086c6f635f7479706518052001280e32152e546869726456332e4c6f63" .
            "6174696f6e547970652a320a0c4c6f636174696f6e5479706512050a015f" .
            "100012070a03475053100112070a034e4554100212090a054f5448455210" .
            "03620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

